apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: sa-p8
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: sa-platform
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollout-analysis
  namespace: sa-p8
  labels:
    app.kubernetes.io/name: rollout-analysis
    app.kubernetes.io/part-of: sa-platform
automountServiceAccountToken: false
