apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sa-platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: practica-8
spec:
  project: default
  source:
    repoURL: https://github.com/Jeremy142OO4/Practicas-SA-B-202300644-gitops.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-p8
  ignoreDifferences:
    - group: ""
      kind: Service
      namespace: sa-p8
      name: api-gateway-stable
      jsonPointers:
        - /spec/selector
    - group: ""
      kind: Service
      namespace: sa-p8
      name: api-gateway-canary
      jsonPointers:
        - /spec/selector
    - group: kyverno.io
      kind: ClusterPolicy
      jsonPointers:
        - /spec/admission
        - /spec/emitWarning
        - /spec/rules/0/skipBackgroundRequests
        - /spec/rules/0/validate/allowExistingViolations
        - /spec/rules/0/verifyImages
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
