apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orders-ms-secrets
  namespace: sa-p9
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: p9-gcp-secrets
    kind: ClusterSecretStore
  target:
    name: orders-ms-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: p9-202300644-orders-database-url
    - secretKey: RABBITMQ_URL
      remoteRef:
        key: p9-202300644-rabbitmq-url
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: p9-202300644-db-password
    - secretKey: RABBITMQ_DEFAULT_PASSWORD
      remoteRef:
        key: p9-202300644-rabbitmq-password

