apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: sa-p8
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: sa-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: sa-platform-secrets
    kind: ClusterSecretStore
  target:
    name: api-gateway-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: sa-p8/api-gateway
        property: JWT_SECRET
    - secretKey: INTERNAL_API_TOKEN
      remoteRef:
        key: sa-p8/api-gateway
        property: INTERNAL_API_TOKEN
