apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: sa-p8
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: sa-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: sa-p7-kubernetes
    kind: ClusterSecretStore
  target:
    name: api-gateway-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: auth-ms-secret
        property: JWT_SECRET
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: auth-ms-secret
        property: ENCRYPTION_KEY
